source 'https://rubygems.org'

gem 'cucumber', '~> 1.3'
gem 'mediawiki_api', '~> 0.7.0'
gem 'mediawiki_selenium', '~> 1.8'
gem 'minitest', '~> 5.9', '>= 5.9.1'
gem 'page-object', '~> 2.0'
gem 'rake', '11.1.2'
gem 'rspec', '~> 2.99'
gem 'rubocop', '~> 0.43.0'
gem 'selenium-webdriver', '~> 3.1.0'
gem 'watir', '~> 6.2'
